export const IPC_CHANNEL_NAMES = {
  // Renderer → Main (invoke)
  callBackendApi: 'call-backend-api',
  getAppConfig: 'get-app-config',
  getAllAppConfig: 'app-config-getAll',
  setAppConfig: 'set-app-config',
  setManyAppConfig: 'set-app-config-batch',
  resetAppConfig: 'reset-app-config',
  getUserConfig: 'get-user-config',
  setUserConfig: 'set-user-config',
  getAllUserConfig: 'user-config-getAll',
  resetUserConfig: 'reset-user-config',
  getSettingsViewModel: 'get-settings-view-model',
  resolveSettingsPaths: 'resolve-settings-paths',
  showSystemNotification: 'show-system-notification',
  rendererLog: 'renderer-log',
  showOpenDialog: 'show-open-dialog',
  showSaveDialog: 'show-save-dialog',
  showMessagebox: 'show-message-box',
  getFileStats: 'get-file-stats',
  writeFile: 'write-file',
  readFile: 'read-file',
  openPath: 'open-path',
  openDevTools: 'open-dev-tools',
  toggleDevTools: 'toggle-dev-tools',
  getAppInfo: 'get-app-info',
  getFontendBuildInfo: 'get-fontend-build-info',
  readClipboardText: 'read-clipboard-text',
  writeClipboardText: 'write-clipboard-text',
  pathResolve: 'path-resolve',
  // Main → Renderer (send/on)
  appConfigChanged: 'app-config-changed',
  userConfigChanged: 'user-config-changed',
  deviceChange: 'device-change',
  logcatOutput: 'logcat-output',
  logcatStarted: 'logcat-started',
  logcatFinished: 'logcat-finished',
  streamEvent: 'stream-event',
  showQuitDialog: 'show-quit-dialog',
  respondQuitDialog: 'respond-quit-dialog',
  // Backend health & stderr tail (T23)
  backendStderrTail: 'backend-stderr-tail',
  getBackendHealth: 'get-backend-health',
  readElectronLogTail: 'read-electron-log-tail',

  // Update — Renderer → Main
  checkForUpdates: 'check-for-updates',
  downloadUpdate: 'download-update',
  quitAndInstall: 'quit-and-install',

  // Update — Main → Renderer
  updateAvailable: 'update-available',
  updateNotAvailable: 'update-not-available',
  downloadProgress: 'download-progress',
  updateDownloaded: 'update-downloaded',
  updateError: 'update-error',
} as const
